version: "3.7"
services:
  db:
    image: mariadb:10.1
    container_name: flask-mariadb
    volumes:
       - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=flask
    networks:
      - backends
    ports:
      - "3306:3306"
  app:
    build: ./flask
    container_name: flask
    restart: always
    volumes:
      - ./flask:/app
      - ./log/uwsgi:/var/log/uwsgi
    environment:
      - APP_NAME=MyFlaskApp
    networks:
      - backends
      - frontends
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - frontends
    volumes:
      - ./log/nginx:/var/log/nginx
volumes:
    dbdata:
networks:
  backends:
  frontends: